spring.application.name=service-user
spring.config.import=optional:configserver:http://localhost:8888
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

jwt.secret=NexLanceSecretKeyForJWTTokenGenerationAndValidation2026
jwt.expiration=86400000
keycloak.enabled=false