# ===============================
# Application Info
# ===============================
server.port=8084

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/nexlance_service_user?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Eureka
# ===============================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.tn.esprit.pi.nexlance=DEBUG

# ===============================
# Keycloak Configuration
# ===============================
keycloak.enabled=false
keycloak.realm=nexlance-realm
keycloak.auth-server-url=http://localhost:8180
keycloak.ssl-required=none
keycloak.resource=nexlance-client
keycloak.credentials.secret=your-client-secret-here
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true

# ===============================
# Keycloak Admin Client
# ===============================
keycloak.admin.server-url=http://localhost:8180
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin

# ===============================
# JWT Configuration
# ===============================
jwt.secret=NexLanceSecretKeyForJWTTokenGenerationAndValidation2026
jwt.expiration=86400000

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
file.upload-dir=uploads
backend.url=http://localhost:8084

# Exposition des endpoints pour Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}